# Data Loading, Cleaning & Export

### Importazione Librerie

In [1]:
import numpy as np
import pandas as pd
import requests

### Caricamento Dati

In [27]:
CSV_files = {
    "customers":           r"dataset/olist_customers_dataset.csv",
    "geolocation_dataset": r"dataset/olist_geolocation_dataset.csv",
    "order_items":         r"dataset/olist_order_items_dataset.csv",
    "order_payments":      r"dataset/olist_order_payments_dataset.csv",
    "order_review":        r"dataset/olist_order_reviews_dataset.csv",
    "order_dataset":       r"dataset/olist_orders_dataset.csv",
    "list_product":        r"dataset/olist_products_dataset.csv",
    "list_seller":         r"dataset/olist_sellers_dataset.csv",
    "product_category":    r"dataset/product_category_name_translation.csv"
}

dataframes = {name: pd.read_csv(path) for name, path in CSV_files.items()}

df_customers           = dataframes["customers"]
df_orders_items        = dataframes["order_items"]
df_order_payments      = dataframes["order_payments"]
df_order_review        = dataframes["order_review"]
df_order_dataset       = dataframes["order_dataset"]
df_list_product        = dataframes["list_product"]
df_list_seller         = dataframes["list_seller"]
df_product_category    = dataframes["product_category"]
df_geolocation_dataset = dataframes["geolocation_dataset"]

### Analisi Preliminare

In [28]:
# Stampa un riepilogo di ogni csv con la sua shape, i missing values e i duplicati.
def quick_overview(df, name):

    # Nome DF
    print(f"{name}")
    print(f"Shape: {df.shape}")

    # Valori nulli
    nulls = df.isna().sum()
    nulls = nulls[nulls > 0]
    if len(nulls) > 0:
        print(f"Valori nulli:\n{nulls.to_string()}\n")
    else:
        print("Nessun valore nullo\n")

for name, df in dataframes.items():
    quick_overview(df, name)

customers
Shape: (99441, 5)
Nessun valore nullo

geolocation_dataset
Shape: (1000163, 5)
Nessun valore nullo

order_items
Shape: (112650, 7)
Nessun valore nullo

order_payments
Shape: (103886, 5)
Nessun valore nullo

order_review
Shape: (99224, 7)
Valori nulli:
review_comment_title      87656
review_comment_message    58247

order_dataset
Shape: (99441, 8)
Valori nulli:
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965

list_product
Shape: (32951, 9)
Valori nulli:
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2

list_seller
Shape: (3095, 4)
Nessun valore nullo

product_category
Shape: (71, 2)
Nessun valore nullo

### PULIZIA: df_list_product

In [ ]:
# 1) Droppiamo le colonne (peso, misure)
# 2) Uniamo la traduzione inglese della categoria.

# 1
df_list_product = df_list_product.drop(
    columns=['product_name_lenght', 'product_width_cm',
             'product_height_cm', 'product_length_cm', 'product_weight_g']
)

# 2
df_list_product = (
    df_list_product
    .merge(df_product_category, on='product_category_name', how='left')
)

df_list_product.info()
df_list_product.sample(2)

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_id                     32951 non-null  str
 1   product_category_name          32341 non-null  str
 2   product_description_lenght     32341 non-null  float64
 3   product_photos_qty             32341 non-null  float64
 4   product_category_name_english  32328 non-null  str
dtypes: float64(2), str(3)
memory usage: 1.3 MB

,product_id,product_category_name,product_description_lenght,product_photos_qty,product_category_name_english
10367,32b2a45c7698faf599ad250c65f6f633,consoles_games,1194.0,1.0,consoles_games
25302,eddecafe978fc89774f82f552197bb08,esporte_lazer,152.0,3.0,sports_leisure

### WEB SCRAPING: traduzione delle categorie prodotto che non avevano traduzione nella dataframe df_product_category

In [30]:
# Traduciamo con Selenium le categorie portoghesi senza traduzione inglese
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# Troviamo i nomi portoghesi che non hanno traduzione nel dataframe df_product_category
traduzione_mancante = df_list_product['product_category_name_english'].isna()
nomi_mancanti = df_list_product[traduzione_mancante]['product_category_name'].dropna().unique()
print(f"Categorie da tradurre ({len(nomi_mancanti)}): \n{nomi_mancanti}\n")

Categorie da tradurre (2):
<StringArray>
['pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos']
Length: 2, dtype: str

In [32]:
# Apre Google Translate nel browser e restituisce la traduzione
# dal portoghese all'inglese del testo passato, formattata in snake_case.
def traduci_categoria(testo):

    # Costruisce l'URL di Google Translate con i parametri: lingua portoghese (pt), lingua inglese (en) e testo
    url = f"https://translate.google.com/?sl=pt&tl=en&text={testo}&op=translate"
    driver.get(url)
    
    # Attende 2 secondi che la pagina carichi e la traduzione appaia
    time.sleep(2)

    # Accetta i cookie se il popup è presente
    try:
        accept_button = driver.find_element(By.XPATH, "//button[.//span[text()='Accept all']]")
        accept_button.click()
        time.sleep(2)
    except:
        pass  # Il popup non è presente, continua normalmente
    
    # Trova l'elemento HTML che contiene il testo tradotto
    risultato = driver.find_element(By.XPATH, "//span[@jsname='W297wb']")
    
    # Converte in minuscolo e sostituisce gli spazi con underscore
    traduzione = risultato.text.lower().replace(' ', '_')
    return traduzione

# Avvia Firefox
driver = webdriver.Firefox()

# Dizionario che conterrà le traduzioni: {nome_portoghese: traduzione_inglese}
traduzioni_manuali = {}

# Itera sui nomi di categoria mancanti di traduzione
for nome in nomi_mancanti:
    traduzione = traduci_categoria(nome)
    traduzioni_manuali[nome] = traduzione
    print(f"{nome}  →  {traduzione}")
    time.sleep(1)

# Chiude il browser al termine delle traduzioni
driver.quit()

# Aggiorna il DataFrame: per ogni categoria tradotta,
# riempie i valori NaN nella colonna 'product_category_name_english'
for nome, traduzione in traduzioni_manuali.items():
    df_list_product.loc[
        df_list_product['product_category_name'] == nome,
        'product_category_name_english'
    ] = traduzione

df_list_product.info()

pc_gamer  →  gaming_pc
portateis_cozinha_e_preparadores_de_alimentos  →  portateis_kitchen_e_food_preparators
<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_id                     32951 non-null  str
 1   product_category_name          32341 non-null  str
 2   product_description_lenght     32341 non-null  float64
 3   product_photos_qty             32341 non-null  float64
 4   product_category_name_english  32341 non-null  str
dtypes: float64(2), str(3)
memory usage: 1.3 MB

### RICHIESTA API: Ottenere il tasso di conversione da Real Brasiliano (BRL) a Euro (EUR)

In [35]:
url = 'https://v6.exchangerate-api.com/v6/ee8e65018f5adf36f58283bd/latest/EUR'
oae = requests.get(url)
print(oae.status_code)

200

In [36]:
EUR_BRL=oae.json()['conversion_rates']['BRL']
print(f"Tasso di cambio attuale da BRL a EUR: {EUR_BRL}")

Tasso di cambio attuale da BRL a EUR: 6.0747

### PULIZIA: df_orders_items

In [ ]:
# 1) Escludiamo gli items con product_id in product_id_to_delete
# 2) Convertiamo le colonne in real brasiliano in euro

# 1
df_orders_items['shipping_limit_date'] = pd.to_datetime(
    df_orders_items['shipping_limit_date']
)

# 2
# Conversione in euro di price e freight_value
df_orders_items['eur_price']=df_orders_items['price']/EUR_BRL
df_orders_items['eur_freight_value']=df_orders_items['freight_value']/EUR_BRL
# Rimozione colonne in real breasiliano
df_orders_items=df_orders_items.drop(['price','freight_value'],axis=1)

df_orders_items.info()
df_orders_items.sample(2)

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   eur_price            112650 non-null  float64
 6   eur_freight_value    112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,eur_price,eur_freight_value
37390,54dd1a0a63644a70b3a1ad75cbdbcede,1,084e67a8fc02c8ac030154244701f1c5,1900267e848ceeba8fa32d80c1a5f5a8,2018-06-27 08:16:35,3.619932,3.004264
25611,3a353ddf8b0cac74d4b4376f526283cd,1,cf600a2ef17c0e0d1ab1f65b0b6420f1,14a08204d03bb6b6bde8029f801ae0eb,2018-05-31 05:30:52,9.877031,1.835482

### PULIZIA: df_order_dataset

In [ ]:
# 1) Conversione delle colonne data in datetime

# 2) delivery_delay_days : differenza tra consegna effettiva e stimata
#    (positivo = in ritardo, negativo = in anticipo)
#    actual_delivery_days: giorni totali dall'acquisto alla consegna

# 1
date_cols = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]
for col in date_cols:
    df_order_dataset[col] = pd.to_datetime(df_order_dataset[col])

# 2
df_order_dataset['delivery_delay_days'] = (
    df_order_dataset['order_delivered_customer_date'] -
    df_order_dataset['order_estimated_delivery_date']
).dt.days
df_order_dataset['actual_delivery_days'] = (
    df_order_dataset['order_delivered_customer_date'] -
    df_order_dataset['order_purchase_timestamp']
).dt.days

df_order_dataset.info()
df_order_dataset.sample(2)

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
 8   delivery_delay_days            96476 non-null  float64
 9   actual_delivery_days           96476 non-null  float64
dtypes: datetime64[us](5), float64(2), str(3)
memory usage: 7.6 MB

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,actual_delivery_days
65279,7f8f6e7d331e83effb58aa14f32cad44,45127f59fac3645efb3f2c3c185bf0da,delivered,2017-03-26 10:23:11,2017-03-26 10:35:12,2017-03-30 18:46:10,2017-04-10 07:37:54,2017-04-13,-3.0,14.0
38758,3ffadf14829f9c35c258e08bb1982a70,60acefff7e20a4ee4981616d545ed441,delivered,2017-06-30 22:53:04,2017-07-04 04:25:15,2017-07-04 10:37:34,2017-07-28 18:27:59,2017-08-03,-6.0,27.0

### PULIZIA: df_order_review

In [38]:
# 1) Conversione della colonna review_creation_date in datetime
# 2) Droppiamo le colonne (review_comment_title, review_comment_message)

# 1
df_order_review['review_creation_date'] = pd.to_datetime(
    df_order_review['review_creation_date']
)

# 2
df_order_review = df_order_review.drop(columns= ['review_comment_title', 'review_comment_message'])

df_order_review.sample(2)

,review_id,order_id,review_score,review_creation_date,review_answer_timestamp
28844,1a96dd0d139a0471b31076e241553767,2235b8528768ef6863fd3f90a50521a9,3,2018-03-16,2018-03-16 23:54:12
54482,cedf655149bc1c7b96aa85193ab695ee,0178ff2480e2e8fb84d456dd3dc3d777,5,2018-03-29,2018-03-30 00:21:59

### PULIZIA: df_order_payments

In [ ]:
# Per un ordine ci sono diverse righe di pagamenti
# Aggreghiamo per order_id

df_order_payments = (
    df_order_payments
    .groupby('order_id', as_index=False)
    .agg(
        total_payment_value= ('payment_value', 'sum'),
        payment_installments= ('payment_installments', 'max'),
        payment_type         = ('payment_type', 'first')
    )
)
df_order_payments.sample(2)

,order_id,total_payment_value,payment_installments,payment_type
72422,ba8dd052f0697464c9b19669d50cf248,33.10,2,credit_card
47050,794aed17c07925f8c6138132f58bacb0,175.77,4,credit_card

In [28]:
df_order_payments['eur_total_payment_value']=round(df_order_payments['total_payment_value']/EUR_BRL,2)#convesrione
df_order_payments=df_order_payments.drop(['total_payment_value'],axis=1)

In [29]:
df_order_payments['order_id'].nunique()

99440

### PULIZIA:df_geolocation

In [30]:
# Coordinate del Brasile
brazil = {
    "lat_min": -34.0, "lat_max": 5.0,
    "lng_min": -75.0, "lng_max": -28.0
}

# Filtra coordinate fuori dal Brasile
df_geolocation_clean = df_geolocation_dataset[
    df_geolocation_dataset["geolocation_lat"].between(brazil["lat_min"], brazil["lat_max"]) &
    df_geolocation_dataset["geolocation_lng"].between(brazil["lng_min"], brazil["lng_max"])
].copy()

# Raggruppa per zip code (media lat/lng, primo valore per città e stato)
df_geolocation_dataset = (
    df_geolocation_clean
    .groupby('geolocation_zip_code_prefix', as_index=False)
    .agg(
        geolocation_lat   = ('geolocation_lat',   'mean'),
        geolocation_lng   = ('geolocation_lng',   'mean'),
        geolocation_city  = ('geolocation_city',  'first'),
        geolocation_state = ('geolocation_state', 'first')
    )
)

df_geolocation_dataset.info()
df_geolocation_dataset.sample(2)

<class 'pandas.DataFrame'>
RangeIndex: 19011 entries, 0 to 19010
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   geolocation_zip_code_prefix  19011 non-null  int64
 1   geolocation_lat              19011 non-null  float64
 2   geolocation_lng              19011 non-null  float64
 3   geolocation_city             19011 non-null  str
 4   geolocation_state            19011 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 742.7 KB

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
5491,15056,-20.774165,-49.340918,sao jose do rio preto,SP
8000,29807,-18.586568,-40.887041,monte sinai,ES

### PULIZIA: df_list_seller

In [31]:
df_list_seller=df_list_seller.rename(columns={'seller_zip_code_prefix':'geolocation_zip_code_prefix'})
df_list_seller.sample(3)

,seller_id,geolocation_zip_code_prefix,seller_city,seller_state
764,1caf283236cd69af44cbc09a0a1e7d32,26020,nova iguacu,RJ
2596,0f519b0d2e5eb2227c93dd25038bfc01,14940,ibitinga,SP
1946,392353362d22cc2c236e1ee81ff19890,89069,blumenau,SC

### PULIZIA: df_customers

In [32]:
df_customers=df_customers.rename(columns={'customer_zip_code_prefix':'geolocation_zip_code_prefix'})
df_customers.sample(3)

,customer_id,customer_unique_id,geolocation_zip_code_prefix,customer_city,customer_state
39947,f6ec8e3d19c8c405c7839b0389c5bb7b,71d2dbb6d2f52d568ca9d69c815a4331,1330,sao paulo,SP
70412,10b6ca8551febff6407d7331aa0c95e8,b3446540ddd2f45621cc3b34b6b1b5f5,89010,blumenau,SC
52455,d3a44fd152f8d7bf1fc08b3bd710f15d,5219a75dd09b1cf3c7df129fe720365b,13905,amparo,SP

### EXPORT: tutti i dataframe puliti nella cartella output

In [ ]:
import os

# Crea la cartella output se non esiste
os.makedirs("output", exist_ok=True)

dataframes_to_export = {
    "list_product":        df_list_product,
    "orders_items":        df_orders_items,
    "order_dataset":       df_order_dataset,
    "order_review":        df_order_review,
    "order_payments":      df_order_payments,
    "geolocation_dataset": df_geolocation_dataset,
    "list_seller":         df_list_seller,
    "customers":           df_customers,
}

for name, df in dataframes_to_export.items():
    df.to_csv(f"output/{name}.csv", index=False)

### Dataframe global (aggregazione per ordini)

In [33]:
# 1. Merge fra list_seller e geolocation_clean
df_seller_geo = df_list_seller.merge(
    df_geolocation_clean,
    on='geolocation_zip_code_prefix',
    how='left'
)
#dal merge ci sono 7 valori nulli per lat, lng e state >> rimpiazzo i valori con 0 e missing
df_seller_geo['geolocation_lat'] = df_seller_geo['geolocation_lat'].fillna(0)
df_seller_geo['geolocation_lng'] = df_seller_geo['geolocation_lng'].fillna(0)
df_seller_geo['geolocation_city'] = df_seller_geo['geolocation_city'].fillna('missing')
df_seller_geo['geolocation_state'] = df_seller_geo['geolocation_state'].fillna('missing')

# 2. Merge fra customers e geolocation_clean
df_customer_geo = df_list_seller.merge(
    df_geolocation_clean,
    on='geolocation_zip_code_prefix', 
    how='left'
)
#dal merge ci sono 7 valori nulli per lat, lng e state >> rimpiazzo i valori con 0 e missing
df_customer_geo['geolocation_lat'] = df_customer_geo['geolocation_lat'].fillna(0)
df_customer_geo['geolocation_lng'] = df_customer_geo['geolocation_lng'].fillna(0)
df_customer_geo['geolocation_city'] = df_customer_geo['geolocation_city'].fillna('missing')
df_customer_geo['geolocation_state'] = df_customer_geo['geolocation_state'].fillna('missing')

# 3. Aggregazione order_items per order_id
agg_orders_items = (df_orders_items.groupby('order_id', as_index = False).agg(
    total_items=('order_item_id', 'count'),       # numero di prodotti venduti
    total_price=('eur_price', 'sum'),                 # somma prezzi
    freight_total=('eur_freight_value', 'sum'),       # somma costi spedizione
    freight_avg=('eur_freight_value', 'mean'),        # media costi spedizione
    first_shipping_limit=('shipping_limit_date', 'min')  # primo limite spedizione
)
)

# 4. Aggregazione order_payments per order_id
agg_order_payments = (
    df_order_payments
    .groupby('order_id', as_index=False)
    .agg(
        total_payment_value= ('eur_total_payment_value', 'sum'),
        payment_installments= ('payment_installments', 'max'),
        payment_type         = ('payment_type', 'first')
    )
)

# 5. Aggregazione order_review per order_id
agg_order_review = (
    df_order_review
    .groupby('order_id', as_index=False)
    .agg(
    avg_review=('review_score', 'mean'),
    num_reviews=('review_score', 'count'),
    firs_review_date = ('review_creation_date', 'min'),
    first_review_answer = ('review_answer_timestamp', 'min')
    )
)

# 6. Aggregazione list_product per order_id
agg_list_products = (
    df_orders_items
    .merge(df_list_product, on='product_id', how='left')
    .groupby('order_id', as_index=False)
    .agg(
        num_products=('product_id', 'count'),
        num_categories=('product_category_name_english', 'nunique')
    )
)

# . Aggregazione list_seller per order_id
agg_seller = (
    df_orders_items
    .merge(df_seller_geo, on='seller_id', how='left')
    .groupby('order_id', as_index=False)
    .agg(
        num_sellers = ('seller_id', 'count'),
        geolocation_zip_code_prefix = ('geolocation_zip_code_prefix', 'first'),
        seller_city = ('seller_city', 'first'),
        seller_state = ('seller_state', 'first')
    )   
)        

# Merge
df_global = df_order_dataset.merge(df_customers, on='customer_id', how='left') \
                     .merge(agg_orders_items, on='order_id', how='left') \
                     .merge(agg_order_review, on='order_id', how='left') \
                     .merge(agg_order_payments, on='order_id', how='left') \
                     .merge(agg_list_products, on='order_id', how='left') \
                     .merge(agg_seller, on='order_id', how='left')

In [34]:
df_global.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 32 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
 8   delivery_delay_days            96476 non-null  float64
 9   actual_delivery_days           96476 non-null  float64
 10  customer_unique_id             99441 non-null  str
 11  geolocation_zip_code_prefix_x  99441 non-null  int64
 12  customer_city                  99441 non-null  str
 13  customer_state                 99441 non-null  str
 14  total_items                    98666 non-null  float64
 15  total_price                    98666 non-null  float64
 16  freight_total                  98666 non-null  float64
 17  freight_avg                    98666 non-null  float64
 18  first_shipping_limit           98666 non-null  datetime64[us]
 19  avg_review                     98673 non-null  float64
 20  num_reviews                    98673 non-null  float64
 21  firs_review_date               98673 non-null  datetime64[us]
 22  first_review_answer            98673 non-null  str
 23  total_payment_value            99440 non-null  float64
 24  payment_installments           99440 non-null  float64
 25  payment_type                   99440 non-null  str
 26  num_products                   98666 non-null  float64
 27  num_categories                 98666 non-null  float64
 28  num_sellers                    98666 non-null  float64
 29  geolocation_zip_code_prefix_y  98666 non-null  float64
 30  seller_city                    98666 non-null  str
 31  seller_state                   98666 non-null  str
dtypes: datetime64[us](7), float64(14), int64(1), str(10)
memory usage: 24.3 MB

In [35]:
#PULIZIA DATI

# 1768 ordini non hanno review - Inserisco 0 al posto del valore nullo
df_global['avg_review'] = df_global['avg_review'].fillna(0)
df_global['num_reviews'] = df_global['num_reviews'].fillna(0)
# Feature booleana che identifica 0 come valore nullo e non come score
df_global['has_review'] = df_global['num_reviews'] > 0

# Controllo i valori nulli (97277)
cols_items_seller = [
    'total_items', 'total_price', 'freight_total', 'freight_avg',
    'num_products', 'num_categories', 'num_sellers',
    'seller_city', 'seller_state', 'geolocation_zip_code_prefix_y'
]
rows_with_nulls = df_global[df_global[cols_items_seller].isna().any(axis=1)]
same_nulls = rows_with_nulls[cols_items_seller].isna().all(axis=1)

#Sostituisco i valori stringa con "unknown"
cat_cols = ['seller_city', 'seller_state']
df_global[cat_cols] = df_global[cat_cols].fillna('unknown')
df_global['has_items'] = df_global['total_items'] > 0

# Sostituisco null nei valori numerici dei pagamenti
df_global['total_payment_value'] = df_global['total_payment_value'].fillna(0)
df_global['payment_installments'] = df_global['payment_installments'].fillna(0)
# Sostituisco null nel metodo di pagamento con 'unknown'
df_global['payment_type'] = df_global['payment_type'].fillna('unknown')
# Facoltativo: feature booleana se ordine ha pagamento
df_global['has_payment'] = df_global['total_payment_value'] > 0

In [36]:
df_global.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 35 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
 8   delivery_delay_days            96476 non-null  float64
 9   actual_delivery_days           96476 non-null  float64
 10  customer_unique_id             99441 non-null  str
 11  geolocation_zip_code_prefix_x  99441 non-null  int64
 12  customer_city                  99441 non-null  str
 13  customer_state                 99441 non-null  str
 14  total_items                    98666 non-null  float64
 15  total_price                    98666 non-null  float64
 16  freight_total                  98666 non-null  float64
 17  freight_avg                    98666 non-null  float64
 18  first_shipping_limit           98666 non-null  datetime64[us]
 19  avg_review                     99441 non-null  float64
 20  num_reviews                    99441 non-null  float64
 21  firs_review_date               98673 non-null  datetime64[us]
 22  first_review_answer            98673 non-null  str
 23  total_payment_value            99441 non-null  float64
 24  payment_installments           99441 non-null  float64
 25  payment_type                   99441 non-null  str
 26  num_products                   98666 non-null  float64
 27  num_categories                 98666 non-null  float64
 28  num_sellers                    98666 non-null  float64
 29  geolocation_zip_code_prefix_y  98666 non-null  float64
 30  seller_city                    99441 non-null  str
 31  seller_state                   99441 non-null  str
 32  has_review                     99441 non-null  bool
 33  has_items                      99441 non-null  bool
 34  has_payment                    99441 non-null  bool
dtypes: bool(3), datetime64[us](7), float64(14), int64(1), str(10)
memory usage: 24.6 MB

In [37]:
df_global.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'delivery_delay_days', 'actual_delivery_days', 'customer_unique_id',
       'geolocation_zip_code_prefix_x', 'customer_city', 'customer_state',
       'total_items', 'total_price', 'freight_total', 'freight_avg',
       'first_shipping_limit', 'avg_review', 'num_reviews', 'firs_review_date',
       'first_review_answer', 'total_payment_value', 'payment_installments',
       'payment_type', 'num_products', 'num_categories', 'num_sellers',
       'geolocation_zip_code_prefix_y', 'seller_city', 'seller_state',
       'has_review', 'has_items', 'has_payment'],
      dtype='str')